env:
    global:
        - PACKAGE="User" # Package name
        - SUBLIME_TEXT_VERSION="3"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          python: 3.3
        # - os: osx
        #  language: generic


before_install:
    - git clone https://github.com/guillermooo/Six.git ../Six
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # clean target directory
    - rm -rf $STP/User/*
    # enable Six package
    - ln -s `pwd`/../Six "$STP/Six"
    # enable our package
    - ln -s `pwd` "$STP/User/six"
    # make sure Sublime Text will load our package
    - echo "from User.six.surround import *\n\ndef plugin_loaded():\n    surround()\n" > "$STP/User/sixrc.py"
    # configure UnitTesting
    - >
        echo { \"tests_dir\": \"./six/tests\" } > "$STP/User/unittesting.json"


script:
    # run tests with test coverage report
    - sh travis.sh run_tests # --coverage
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    # remove the following if `coveralls` is not needed
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python || brew upgrade python;
      fi
    - pip3 install python-coveralls;
    - pip3 install codecov;
    - coveralls
    - codecov

notifications:
    email: false
